name: Laravel-docker

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  laravel-docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@2.25.5
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Copy .env file
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag zhonghaibin/my-app:2.0
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
      - name: Push Docker images
        run: docker push  zhonghaibin/my-app:2.0

      - name: SSH command
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{secrets.NAS_HOST}}
            username: ${{secrets.NAS_USERNAME}}
            port: ${{secrets.NAS_PORT}}
            password: ${{secrets.NAS_PASSWORD}}
            script: | # 重启更新镜像
               /usr/local/bin/docker pull zhonghaibin/my-app:2.0
               /usr/local/bin/docker stop my-app
               /usr/local/bin/docker rm my-app
               /usr/local/bin/docker run --name=my-app --link=mariadb -d -p 8000:8000  -v /volume3/docker/my-app/uploads/:/app/public/uploads zhonghaibin/my-app:2.0
               /usr/local/bin/docker cp /volume3/docker/my-app/.env my-app:/app/.env
